<?php include 'includes/header.php' ?>
  <div class="blog-post">
	<h2 class="blog-post-title">International PHP Conference 2015</h2>
	<p class="blog-post-meta">January 1, 2015 by <a href="#">Mark</a></p>
	  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut diam aliquet, blandit urna sit amet, molestie arcu. Sed venenatis justo ut ipsum ultricies laoreet. Suspendisse potenti. Ut ac nunc at augue aliquam mollis. Curabitur fringilla iaculis orci, sit amet consectetur quam pellentesque at. Aliquam efficitur nunc massa, ac accumsan risus lobortis non. Morbi tellus nisi, gravida vitae dolor a, dignissim aliquam nulla. Nunc at sem mattis, lacinia lectus dignissim, egestas tortor.</p>
	  <p>Fusce maximus ipsum ultricies lectus egestas rutrum non sed libero. Nulla laoreet feugiat massa at malesuada. Nulla risus mauris, hendrerit at orci vitae, commodo ultricies felis. Proin ipsum odio, sagittis a elit vel, condimentum dapibus ex. Vestibulum sed pulvinar metus. Vestibulum et lobortis eros, et viverra nisl. Praesent ut iaculis felis. Nullam id commodo metus. Nam aliquet quam id metus malesuada, ac blandit leo ornare. Nam aliquam vestibulum lorem, ac consectetur turpis sagittis eu.</p>
	  <p>Nulla tincidunt turpis sit amet ante facilisis viverra. Proin eu lobortis enim. Donec et eros in neque egestas ultricies. Cras accumsan, purus et maximus placerat, risus lorem cursus nisl, lobortis elementum ante enim ut ante. Fusce consectetur porttitor lacus, et egestas eros condimentum nec. Quisque eget suscipit nunc. Fusce fringilla felis libero, rhoncus sagittis tortor rhoncus at. Fusce faucibus neque diam, non imperdiet nunc ullamcorper nec. Sed tincidunt augue ante, quis eleifend diam fringilla in. Aliquam elementum nisl odio, vel tristique dolor laoreet ut. Cras efficitur cursus justo id accumsan. Proin volutpat malesuada euismod. Duis vestibulum sapien vitae dapibus tempor.</p>
  </div><!-- /.blog-post -->
<?php include 'includes/footer.php' ?>        
